/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktiviteRouteImport } from './routes/aktivite'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as CariHesapRouteImport } from './routes/cari-hesap'
import { Route as DosyalarRouteImport } from './routes/dosyalar'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HatirlatmalarRouteImport } from './routes/hatirlatmalar'
import { Route as MasraflarRouteImport } from './routes/masraflar'
import { Route as MuvekkillerRouteImport } from './routes/muvekkiller'
import { Route as RaporlarRouteImport } from './routes/raporlar'
import { Route as TahsilatlarRouteImport } from './routes/tahsilatlar'
import { Route as TaksitlerRouteImport } from './routes/taksitler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktiviteRoute = AktiviteRouteImport.update({
  id: '/aktivite',
  path: '/aktivite',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const CariHesapRoute = CariHesapRouteImport.update({
  id: '/cari-hesap',
  path: '/cari-hesap',
  getParentRoute: () => rootRouteImport,
} as any)
const DosyalarRoute = DosyalarRouteImport.update({
  id: '/dosyalar',
  path: '/dosyalar',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HatirlatmalarRoute = HatirlatmalarRouteImport.update({
  id: '/hatirlatmalar',
  path: '/hatirlatmalar',
  getParentRoute: () => rootRouteImport,
} as any)
const MasraflarRoute = MasraflarRouteImport.update({
  id: '/masraflar',
  path: '/masraflar',
  getParentRoute: () => rootRouteImport,
} as any)
const MuvekkillerRoute = MuvekkillerRouteImport.update({
  id: '/muvekkiller',
  path: '/muvekkiller',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporlarRoute = RaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => rootRouteImport,
} as any)
const TahsilatlarRoute = TahsilatlarRouteImport.update({
  id: '/tahsilatlar',
  path: '/tahsilatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const TaksitlerRoute = TaksitlerRouteImport.update({
  id: '/taksitler',
  path: '/taksitler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesap': typeof CariHesapRoute
  '/dosyalar': typeof DosyalarRoute
  '/giris': typeof GirisRoute
  '/hatirlatmalar': typeof HatirlatmalarRoute
  '/masraflar': typeof MasraflarRoute
  '/muvekkiller': typeof MuvekkillerRoute
  '/raporlar': typeof RaporlarRoute
  '/tahsilatlar': typeof TahsilatlarRoute
  '/taksitler': typeof TaksitlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesap': typeof CariHesapRoute
  '/dosyalar': typeof DosyalarRoute
  '/giris': typeof GirisRoute
  '/hatirlatmalar': typeof HatirlatmalarRoute
  '/masraflar': typeof MasraflarRoute
  '/muvekkiller': typeof MuvekkillerRoute
  '/raporlar': typeof RaporlarRoute
  '/tahsilatlar': typeof TahsilatlarRoute
  '/taksitler': typeof TaksitlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivite': typeof AktiviteRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesap': typeof CariHesapRoute
  '/dosyalar': typeof DosyalarRoute
  '/giris': typeof GirisRoute
  '/hatirlatmalar': typeof HatirlatmalarRoute
  '/masraflar': typeof MasraflarRoute
  '/muvekkiller': typeof MuvekkillerRoute
  '/raporlar': typeof RaporlarRoute
  '/tahsilatlar': typeof TahsilatlarRoute
  '/taksitler': typeof TaksitlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivite'
    | '/ayarlar'
    | '/bildirimler'
    | '/cari-hesap'
    | '/dosyalar'
    | '/giris'
    | '/hatirlatmalar'
    | '/masraflar'
    | '/muvekkiller'
    | '/raporlar'
    | '/tahsilatlar'
    | '/taksitler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivite'
    | '/ayarlar'
    | '/bildirimler'
    | '/cari-hesap'
    | '/dosyalar'
    | '/giris'
    | '/hatirlatmalar'
    | '/masraflar'
    | '/muvekkiller'
    | '/raporlar'
    | '/tahsilatlar'
    | '/taksitler'
  id:
    | '__root__'
    | '/'
    | '/aktivite'
    | '/ayarlar'
    | '/bildirimler'
    | '/cari-hesap'
    | '/dosyalar'
    | '/giris'
    | '/hatirlatmalar'
    | '/masraflar'
    | '/muvekkiller'
    | '/raporlar'
    | '/tahsilatlar'
    | '/taksitler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktiviteRoute: typeof AktiviteRoute
  AyarlarRoute: typeof AyarlarRoute
  BildirimlerRoute: typeof BildirimlerRoute
  CariHesapRoute: typeof CariHesapRoute
  DosyalarRoute: typeof DosyalarRoute
  GirisRoute: typeof GirisRoute
  HatirlatmalarRoute: typeof HatirlatmalarRoute
  MasraflarRoute: typeof MasraflarRoute
  MuvekkillerRoute: typeof MuvekkillerRoute
  RaporlarRoute: typeof RaporlarRoute
  TahsilatlarRoute: typeof TahsilatlarRoute
  TaksitlerRoute: typeof TaksitlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivite': {
      id: '/aktivite'
      path: '/aktivite'
      fullPath: '/aktivite'
      preLoaderRoute: typeof AktiviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari-hesap': {
      id: '/cari-hesap'
      path: '/cari-hesap'
      fullPath: '/cari-hesap'
      preLoaderRoute: typeof CariHesapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosyalar': {
      id: '/dosyalar'
      path: '/dosyalar'
      fullPath: '/dosyalar'
      preLoaderRoute: typeof DosyalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatirlatmalar': {
      id: '/hatirlatmalar'
      path: '/hatirlatmalar'
      fullPath: '/hatirlatmalar'
      preLoaderRoute: typeof HatirlatmalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masraflar': {
      id: '/masraflar'
      path: '/masraflar'
      fullPath: '/masraflar'
      preLoaderRoute: typeof MasraflarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muvekkiller': {
      id: '/muvekkiller'
      path: '/muvekkiller'
      fullPath: '/muvekkiller'
      preLoaderRoute: typeof MuvekkillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raporlar': {
      id: '/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof RaporlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahsilatlar': {
      id: '/tahsilatlar'
      path: '/tahsilatlar'
      fullPath: '/tahsilatlar'
      preLoaderRoute: typeof TahsilatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taksitler': {
      id: '/taksitler'
      path: '/taksitler'
      fullPath: '/taksitler'
      preLoaderRoute: typeof TaksitlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktiviteRoute: AktiviteRoute,
  AyarlarRoute: AyarlarRoute,
  BildirimlerRoute: BildirimlerRoute,
  CariHesapRoute: CariHesapRoute,
  DosyalarRoute: DosyalarRoute,
  GirisRoute: GirisRoute,
  HatirlatmalarRoute: HatirlatmalarRoute,
  MasraflarRoute: MasraflarRoute,
  MuvekkillerRoute: MuvekkillerRoute,
  RaporlarRoute: RaporlarRoute,
  TahsilatlarRoute: TahsilatlarRoute,
  TaksitlerRoute: TaksitlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
